apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}
spec:
  hosts:
    - "{{ .Values.appName }}.npii-aks.dhp-east2us-npe.humana.com"
  gateways:
    - istio-system/ingressgateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.appName }}
            port:
              number: 443